### ISSUE TITLE
Request: Deployed version of ActionManager

### ISSUE THREAD

**Issue by lopez1de** [TheCoCe/SpaceEngineersScripts#1]
Regarding to the MDK documentation if one wants to use your project, it must be deployed to Space Engineers via Visual Studio.
https://github.com/malware-dev/MDK-SE/wiki/Deploying-Your-Script-to-Space-Engineers

Is it possible for you to provide a deployed version of ActionManager to GitHub. Maybe as a release? I would love to test and use your ActionManager without getting into Visual Studio.

Regards and thanks.

**Comment by TheCoCe** [comment]
ActionManager has now been added as a release
